"""Streamlit demo UI for the ArXiv paper Q&A pipeline.

Run with:
    streamlit run app.py
"""

import streamlit as st

from src import config
from src.rag import (
    ask,
    build_embed_model,
    build_es_client,
    build_llm,
    build_reranker,
    corpus_date_range,
)

st.set_page_config(page_title="ArXiv Paper Q&A", page_icon="\U0001F4C4", layout="centered")


@st.cache_resource
def get_es_client():
    return build_es_client()


@st.cache_resource
def get_embed_model():
    return build_embed_model()


@st.cache_resource
def get_reranker():
    return build_reranker()


@st.cache_resource
def get_llm():
    return build_llm()

st.title("\U0001F4C4 ArXiv Paper Q&A")
st.caption(
    "Ask questions over a locally indexed corpus of recent cs.AI / cs.LG papers. "
    "Retrieval is hybrid BM25 + kNN over Elasticsearch, fused with RRF and "
    "re-ranked by a cross-encoder; answers are generated by a local LLM (Ollama) "
    "grounded only in the retrieved paper abstracts."
)

with st.sidebar:
    st.subheader("Corpus")
    try:
        es = get_es_client()
        oldest, newest, count = corpus_date_range(es)
        st.metric("Indexed papers", f"{count:,}")
        st.write(f"**Date range:** {oldest[:10]} to {newest[:10]}")
    except Exception as e:
        st.error(
            f"Could not read the corpus from Elasticsearch at {config.ES_URL}: {e}\n\n"
            f"Is ES running, and has `python -m src.ingest` been run yet?"
        )
    st.divider()
    st.write(f"**Embedding model:** {config.EMBEDDING_MODEL}")
    st.write(f"**Re-ranker:** {config.RERANK_MODEL}")
    st.write(f"**LLM:** {config.OLLAMA_MODEL}")

EXAMPLES = [
    "What are recent approaches to reducing LLM hallucination?",
    "Who are the authors of papers about diffusion models for image generation?",
    "Find paper Steady-State Behavior of Constant-Stepsize Stochastic Approximation: "
    "Gaussian Approximation and Tail Bounds with authors",
    "Compare different approaches to reducing hallucination in LLMs, and list the authors for each",
    "Graph neural networks for molecule property prediction, list authors for each paper",
]

if "question" not in st.session_state:
    st.session_state.question = ""


def set_question(q: str):
    st.session_state.question = q


st.subheader("Try an example")
for example in EXAMPLES:
    st.button(
        example,
        on_click=set_question,
        args=(example,),
        key=f"ex::{example}",
        use_container_width=True,
    )

st.subheader("Or ask your own question")
st.text_area("Question", key="question", height=90, label_visibility="collapsed")

ask_clicked = st.button("Ask", type="primary")

if ask_clicked:
    question = st.session_state.question.strip()
    if not question:
        st.warning("Enter a question first.")
    else:
        with st.spinner("Retrieving papers and generating answer..."):
            try:
                answer = ask(
                    question,
                    es=get_es_client(),
                    embed_model=get_embed_model(),
                    reranker=get_reranker(),
                    llm=get_llm(),
                )
            except Exception as e:
                st.error(f"Something went wrong: {e}")
            else:
                st.markdown(answer)
